// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCWBCmNKRDfGhe2pM4-kkFPitk0mF2korE',
    appId: '1:567633879182:web:3be81a6dcd603f1c87e9df',
    messagingSenderId: '567633879182',
    projectId: 'savour-ai-app',
    authDomain: 'savour-ai-app.firebaseapp.com',
    storageBucket: 'savour-ai-app.firebasestorage.app',
    measurementId: 'G-7PEBNYX1G8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDwVaXyrmEaxA5_t2jVLRcgbFRRhudXgPQ',
    appId: '1:567633879182:android:b6c37c25b65bb04987e9df',
    messagingSenderId: '567633879182',
    projectId: 'savour-ai-app',
    storageBucket: 'savour-ai-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCH6phWxTb3rfT5QbPrOHnWS88H-OBqsXY',
    appId: '1:567633879182:ios:73027dba38b5c2e087e9df',
    messagingSenderId: '567633879182',
    projectId: 'savour-ai-app',
    storageBucket: 'savour-ai-app.firebasestorage.app',
    androidClientId: '567633879182-0bc66h2ofl5kih3ueacdonmq2hl83142.apps.googleusercontent.com',
    iosClientId: '567633879182-c0pk0q8v2ifsd5993odhurupf0dagr0m.apps.googleusercontent.com',
    iosBundleId: 'com.savourai.savourai',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCH6phWxTb3rfT5QbPrOHnWS88H-OBqsXY',
    appId: '1:567633879182:ios:73027dba38b5c2e087e9df',
    messagingSenderId: '567633879182',
    projectId: 'savour-ai-app',
    storageBucket: 'savour-ai-app.firebasestorage.app',
    androidClientId: '567633879182-0bc66h2ofl5kih3ueacdonmq2hl83142.apps.googleusercontent.com',
    iosClientId: '567633879182-c0pk0q8v2ifsd5993odhurupf0dagr0m.apps.googleusercontent.com',
    iosBundleId: 'com.savourai.savourai',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCWBCmNKRDfGhe2pM4-kkFPitk0mF2korE',
    appId: '1:567633879182:web:fed457d203ad2b7987e9df',
    messagingSenderId: '567633879182',
    projectId: 'savour-ai-app',
    authDomain: 'savour-ai-app.firebaseapp.com',
    storageBucket: 'savour-ai-app.firebasestorage.app',
    measurementId: 'G-0LR32Q5YBH',
  );
}